language: node_js
sudo: false
env:
    - CC=gcc-4.8
    - CXX=g++-4.8
addons:
    firefox: latest
    apt:
        sources:
            - google-chrome
            - ubuntu-toolchain-r-test
    packages:
        - google-chrome-stable
        - g++-4.8
        - gcc-4.8
node_js:
    - "4.2"
    - "5.3"
before_script:
    - npm install bower -g
    - npm install gulp -g
    - bower install
script: gulp
