language: node_js
sudo: false
env:
    - CXX=g++-5.3
addons:
    firefox: latest
    apt:
        sources:
            - google-chrome
            - ubuntu-toolchain-r-test
    packages:
        - google-chrome-stable
        - g++-5.3
node_js:
    - "4.2"
    - "5.3"
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    - npm install bower -g
    - npm install gulp -g
    - bower install
script: gulp
