language: node_js
sudo: false
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
node_js:
  - '5.1'
before_script:
  - npm install -g bower gulp
  - npm install
  - bower install
