language: node_js
sudo: false
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
node_js:
    - "4.2"
    - "5.3"
before_script:
    - npm i -g bower gulp
    - bower i
